# Generated by Django 3.2 on 2025-01-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='turno',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en-proceso', 'En Proceso')], default='pendiente', max_length=20),
        ),
    ]
