# Generated by Django 3.2 on 2025-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20250121_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Proceso', 'En Proceso'), ('Completado', 'Completado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='turno',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
