# Generated by Django 3.2 on 2025-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_horarionodisponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
