# Generated by Django 3.2 on 2025-02-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
