# Generated by Django 3.2 on 2025-02-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
