# Generated by Django 3.2 on 2025-02-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_cliente_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='device_id',
        ),
    ]
